### ISSUE TITLE
Column width not adjusted appropriately according to used character

### ISSUE THREAD

**Issue by godfuture** [cloudcmd/console-io#6]
Hi,
I noticed that often the name of folder or files are cut because lack of space. But in the same time, other columns that do not need the space (owner, mode, date) have too much space reserved. It would be better, if short columns only reserve the space they need and spent more space to name column.

**Comment by coderaiser** [comment]
Hi, is it relates to Cloud Commander? What screen size do you have?

**Comment by godfuture** [comment]
> is it relates to Cloud Commander?
Yes.

> What screen size do you have?
Few days ago 22 inch. Now trying it out on 32 inch. Both sizes have this issue. Bad readability even enough pixels available.

**Comment by coderaiser** [comment]
Could you please tell me resolution you are using in pixels, or better add screenshot.

**Comment by godfuture** [comment]
> Could you please tell me resolution you are using in pixels

22 inch = 1680x1050, 32 inch = 2560x1440

-> Screenshot attached, too.
![MuchSpaceUnusedButNameCut](https://user-images.githubusercontent.com/4669278/103159972-24236080-47d0-11eb-93e8-120b04ffdd28.jpg)

**Comment by coderaiser** [comment]
I see, this looks like a bug, and it is a good idea for a Pull Request :).

**Comment by coderaiser** [comment]
Fixed with 76e0eab, landed in [v15.0.1](https://github.com/coderaiser/cloudcmd/releases/tag/v15.0.1) 🎉 .
Is it works for you?

**Comment by godfuture** [comment]
Can´t wait, really great! 
Is there already a docker build? If not, I would setup virtualbox with Linux. But it would take a bit.

**Comment by coderaiser** [comment]
Yep, on [dockerhub](https://hub.docker.com/repository/docker/coderaiser/cloudcmd/general) :).

**Comment by godfuture** [comment]
> Yep, on [dockerhub](https://hub.docker.com/repository/docker/coderaiser/cloudcmd/general) :).

Is it downloading the latest assets? Because the image wasn´t updated since months...

**Comment by godfuture** [comment]
When trying to replace my container, I get the following error:
`OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "/usr/src/app/bin/cloudcmd.js": stat /usr/src/app/bin/cloudcmd.js: no such file or directory: unknown`

Is this related to V15 release? I have not adjusted ENV variables from previous container...

**Comment by godfuture** [comment]
I have tested the issue with new container and it looks much better, as the name section is not cut or in other words I can properly read folder and file names again. Thanks a lot!
